# Generated by Django 5.2.1 on 2025-06-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jfru_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torahphrase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='torahword',
            options={},
        ),
        migrations.RenameField(
            model_name='blessingword',
            old_name='section',
            new_name='blessing',
        ),
        migrations.RenameField(
            model_name='torahverse',
            old_name='portion',
            new_name='torah',
        ),
        migrations.RemoveField(
            model_name='torahphrase',
            name='order',
        ),
        migrations.RemoveField(
            model_name='torahword',
            name='order',
        ),
    ]
