# Generated by Django 5.2.1 on 2025-06-02 12:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jfru_app', '0002_alter_torahphrase_options_alter_torahword_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torahword',
            name='english_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
