# Generated by Django 5.2.1 on 2025-06-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jfru_app', '0003_torahword_english_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torahword',
            name='english_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
